package cm4108.diary.appointment.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName=PersistentDB.TABLE_NAME)
public class Appointment {
	
	public String appointmentId; 
	
	public long dateAndTime;
	
	public int duration;
	
	public String owner;
	
	public String description;
	
	public Appointment() {
		
	}
	
	public Appointment(long dateAndTime, int duration, String owner, String description) {
		this.setDateAndTime(dateAndTime);
		this.setDuration(duration);
		this.setOwner(owner);
		this.setDescription(description);
	}
	

	@DynamoDBHashKey(attributeName="appointmentId")
	@DynamoDBAutoGeneratedKey
	public String getAppointmentId() {
		return appointmentId;
	}

	public void setAppointmentId(String appointmentId) {
		this.appointmentId = appointmentId;
	}

	public long getDateAndTime() {
		return dateAndTime;
	}

	public void setDateAndTime(long dateAndTime) {
		this.dateAndTime = dateAndTime;
	}

	@DynamoDBAttribute(attributeName="duration")
	public int getDuration() {
		return duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@DynamoDBAttribute(attributeName="owner")
	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}
	
	@DynamoDBAttribute(attributeName="description")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public String toString() {
		return "Appointment [appointmentId=" + appointmentId + ", dateAndTime=" + dateAndTime + ", duration=" + duration + ", owner="
				+ owner + ", description=" + description + "]";
	}
	
}
